name : My Portfolio
brand : Tho Vo
description : My blogs and my portfolio
keyword :
url : http://thovo.github.io
email : votuongtho@gmail.com
twitter : tuongtho
github : thovo
author : Vo Tuong Tho
analytics : UA-66551285-1
year : 2015
markdown : kramdown
exclude :
  - node_modules
